zellyk/bug Table row fixed
Fube/Lepine_Inventory_System pull request #7
Opened 2021-12-14 16:21 UTC by zellyk

Fixed table rows so the text wraps instead of overflowing outside the table.

Jira: https://champlainsaintlambert.atlassian.net/browse/PLUMBERS-20

2021-12-16 16:02 UTC, Fube requested changes

2021-12-16 16:02 UTC, Fube commented on UI/pages/items/index.jsx
> +                <td className="!whitespace-normal !break-words">{description}</td>
Consider making this a scoped class

2021-12-16 16:02 UTC, Fube commented on UI/pages/_app.js
> +    "780a6f12d6cab55b9c650ae1a4340a64"
Extract this into an env var

2021-12-19 20:33 UTC, zellyk commented on UI/pages/items/index.jsx
> +                <td className="!whitespace-normal !break-words">{description}</td>
See latest commit.

2021-12-19 22:06 UTC, Fube requested changes

2021-12-19 22:06 UTC, Fube commented on UI/styles/globals.css
> +}
Why not make this into a class?
Assuming **all** `td`s want these classes is a bit odd, especially since you have `!important`

2021-12-19 22:57 UTC, Fube approved these changes
Good stuff

2021-12-19 22:58 UTC, merged